version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.2.0 
      - image: docker:17.05.0-ce-git 
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Testing
          command: docker-compose -f docker-compose-test.yml run docker-cicd