version: 2
jobs:
  test:
    docker:
      - image: circleci/node:9.2.0 //circleci包好的node-container
      - image: docker:17.05.0-ce-git // 包含git的container
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Testing
          command: docker-compose -f docker-compose-test.yml run docker-cicd